// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lovrkabtuuddlpwsrfip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvdnJrYWJ0dXVkZGxwd3NyZmlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzM1MzIsImV4cCI6MjA3NDQ0OTUzMn0.ifgzGiYoUr6Or1TexW_4_kKFxH52Y7PIQWjvD9LqTlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});