// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwgjnqsegocmdfbkiyem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3Z2pucXNlZ29jbWRmYmtpeWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDAwNDIsImV4cCI6MjA2NDYxNjA0Mn0.oTFGU0rxZNHlaNcD6HoIV7Pcq1ZbbsCyzO4e2VJ9eO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);